version: '3.8'

services:
  link-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: link-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_OPTIONS=--max_old_space_size=4096
      - NPM_CONFIG_LEGACY_PEER_DEPS=true
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - link-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  link-network:
    driver: bridge 