version: '3.8'

services:
  link:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    container_name: link-app
    restart: unless-stopped
    ports:
      - "3211:3211"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3211
      - HOST=0.0.0.0
    volumes:
      - ./public/uploads:/app/public/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3211/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 